[package]
name = "dino-park-whoami"
version = "0.0.1"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
oauth2 = "2.0.0-beta.2"
url = "1.7.2"
base64 = "0.10.1"
rand = "0.6.5"
actix-web = { version = "1.0.0-beta.5", features = ["ssl"] }
actix-session = "0.1.0-beta.4"
failure = "0.1.5"
config = "0.9.3"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
futures = "0.1"
